version: '3.4'

services:
  knowledgehub:
    depends_on:
      - mongo
    image: knowledgehub
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_PORT: 27017
      MONGO_USERNAME: 'root'
      MONGO_PASSWORD: 'root'
    ports:
      - 8888:7777
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - /data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: knowledgehub
      MONGO_PORT: 27017

    restart: always
