version: '0.1'
services:
  web:
    depends_on:
      - mongo
    build: './'
    working_dir: '/app'
    volumes:
      - ./:/app
    ports:
      - '7777:7777'
    command: [ "node", "server.js" ]
    networks:
      - web
      - backend
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - MONGO_DATABASE=knowledge-hub

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "7778:27017"
    volumes:
      - /data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=knowledge-hub
    restart: always
    networks:
      - backend
