version: '3.4'

services:
  knowledgehub:
    image: knowledgehub
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7777:7777
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
